[workspace]
members = [
    "crates/yalm-core",
    "crates/yalm-parser",
    "crates/yalm-cache",
    "crates/yalm-engine",
    "crates/yalm-eval",
    "crates/yalm-evolve",
    "crates/yalm-wikt-build",
    "crates/yalm-demo",
]
resolver = "2"
