[package]
name = "dafhne-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
dafhne-core = { path = "../dafhne-core" }
dafhne-parser = { path = "../dafhne-parser" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "3", features = ["json"] }
