[package]
name = "yalm-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
yalm-core = { path = "../yalm-core" }
yalm-parser = { path = "../yalm-parser" }
yalm-cache = { path = "../yalm-cache" }
yalm-engine = { path = "../yalm-engine" }
clap = { version = "4", features = ["derive"] }
